/*
Copyright 2019 The Openshift Evangelists

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	RBACDefinitionv1beta1 "github.com/darkrat/cajadepandora/pkg/apis/RBACDefinition/v1beta1"
	versioned "github.com/darkrat/cajadepandora/pkg/client/clientset/versioned"
	internalinterfaces "github.com/darkrat/cajadepandora/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/darkrat/cajadepandora/pkg/client/listers/RBACDefinition/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RBACDefinitionInformer provides access to a shared informer and lister for
// RBACDefinitions.
type RBACDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.RBACDefinitionLister
}

type rBACDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRBACDefinitionInformer constructs a new informer for RBACDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRBACDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRBACDefinitionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRBACDefinitionInformer constructs a new informer for RBACDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRBACDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacmanagerV1beta1().RBACDefinitions(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacmanagerV1beta1().RBACDefinitions(namespace).Watch(options)
			},
		},
		&RBACDefinitionv1beta1.RBACDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *rBACDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRBACDefinitionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rBACDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&RBACDefinitionv1beta1.RBACDefinition{}, f.defaultInformer)
}

func (f *rBACDefinitionInformer) Lister() v1beta1.RBACDefinitionLister {
	return v1beta1.NewRBACDefinitionLister(f.Informer().GetIndexer())
}
